
title: NOTICE
email: 'fromweru@gmail.com' #provisional; change
description: 
baseurl: ''
url: 'https://onweru.github.io/sonofy/' #provisional
twitter_username: jekyllrb
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
